### ISSUE TITLE
How to import stuff from Meteor into the react folder?

### ISSUE THREAD

**Issue by rclai** [thereactivestack/meteor-webpack-react-kickstart#4]
This might be a dumb question but how do you get `ReactMeteorData` mixin (or anything Meteor-related) inside one of the components inside the `react` folder?

Also, I noticed that since you installed React Router from Meteor and not from the `package.json`, how is it that you knew to import from `'react-router'`?

**Comment by eXon** [comment]
Inside your react folder, you can access any Meteor global variable. Make sure you have the correct package installed in your meteor folder and you can use the `ReactMeteorData` variable.

If you would like to import anything that is from Meteor, you can add externals to your Webpack config:

```javascript
  externals: {
    'react': 'React',
    'react-router': 'ReactRouter'
  },
```

Their is already React because of Meteor package are depending on it and I don't want it twice. For react-router, it is using the Meteor package because it supports SSR out of the box.
